spring:
  application:
    name: vet
  datasource:
    url: jdbc:postgresql://localhost:5432/vet
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
      - "classpath:application-openapi.yml"
  profiles:
    include:
      - openapi
  # Configuración para subida de archivos
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

# Configuración de JWT
app:
  jwt:
    secret: claveSecretaSuperseguraParaJWTQueDebeSerMuyLargaParaSerSegura
    expiration-ms: 86400000
  # Nueva sección para configuración de seguridad
  security:
    max-failed-attempts: 3          # Número máximo de intentos fallidos antes de bloquear
    lock-duration-minutes: 15       # Duración del bloqueo en minutos
    password-expiry-days: 90        # Duración de la validez de la contraseña en días
    reset-token-expiry-minutes: 60  # Duración de la validez del token de restablecimiento en minutos
    password-history-size: 5        # Número de contraseñas antiguas a recordar para evitar reutilización

# Configuración de logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    io:
      swagger:
        v3: DEBUG
    org.springdoc: DEBUG

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuración de almacenamiento de archivos
file:
  storage:
    upload-dir: uploads
    historial-dir: historiales
